# Generated by Django 5.2.5 on 2025-08-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('tema', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=5000)),
                ('organizador', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
