# Generated by Django 5.2.6 on 2025-09-17 00:36

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('pauta', models.CharField(max_length=150)),
                ('sala', models.CharField(max_length=20)),
                ('responsavel', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
            },
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('pauta', models.CharField(max_length=150)),
                ('sala', models.CharField(max_length=20)),
                ('responsavel', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Comite',
                'verbose_name_plural': 'Comites',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=5000)),
                ('organizador', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Grupo_estudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=45)),
                ('local', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Grupo de Estudo',
                'verbose_name_plural': 'Grupos de estudos',
            },
        ),
        migrations.CreateModel(
            name='Nucleos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('pauta', models.CharField(max_length=150)),
                ('sala', models.CharField(max_length=20)),
                ('responsavel', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Núcleo',
                'verbose_name_plural': 'Núcleos',
            },
        ),
        migrations.CreateModel(
            name='Tipo_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo de usuário',
                'verbose_name_plural': 'Tipos de usuários',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(blank=True, max_length=80, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(max_length=120, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tipo_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='siteifc.tipo_user')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('local', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
        migrations.CreateModel(
            name='User_comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.comissao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comissão do Usuário',
                'verbose_name_plural': 'Comissões do Usuário',
            },
        ),
        migrations.CreateModel(
            name='User_comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.comite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comite do Usuário',
                'verbose_name_plural': 'Comites do Usuário',
            },
        ),
        migrations.CreateModel(
            name='User_eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.eventos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento do Usuário',
                'verbose_name_plural': 'Eventos dos Usúario',
            },
        ),
        migrations.CreateModel(
            name='User_grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_de_estudos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.grupo_estudo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo de Estudo do Usuário',
                'verbose_name_plural': 'Grupos de Estudo do Usuário',
            },
        ),
        migrations.CreateModel(
            name='User_nucleos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nucleos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.nucleos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Núcleo do Usuário',
                'verbose_name_plural': 'Núcleos do Usuário',
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('local', models.CharField(max_length=50)),
                ('preco', models.CharField(max_length=9)),
                ('nome_produto', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.CreateModel(
            name='Reservar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venda', models.CharField(max_length=45)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.atendimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vendas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.vendas')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
