# Generated by Django 5.2.5 on 2025-09-04 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteifc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('pauta', models.CharField(max_length=150)),
                ('sala', models.CharField(max_length=20)),
                ('responsavel', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
            },
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('pauta', models.CharField(max_length=150)),
                ('sala', models.CharField(max_length=20)),
                ('responsavel', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Comite',
                'verbose_name_plural': 'Comites',
            },
        ),
        migrations.CreateModel(
            name='Grupo_de_estudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=45)),
                ('local', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Grupo de Estudo',
                'verbose_name_plural': 'Grupos de estudos',
            },
        ),
        migrations.CreateModel(
            name='Nucleos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('pauta', models.CharField(max_length=150)),
                ('sala', models.CharField(max_length=20)),
                ('responsavel', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Núcleo',
                'verbose_name_plural': 'Núcleos',
            },
        ),
        migrations.CreateModel(
            name='Tipo_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo de usuário',
                'verbose_name_plural': 'Tipos de usuários',
            },
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('login', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=30)),
                ('tipo_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.tipo_user')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('local', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.user')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
        migrations.CreateModel(
            name='User_comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.comissao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.user')),
            ],
            options={
                'verbose_name': 'Comissão do Usuário',
                'verbose_name_plural': 'Comissões do Usuário',
            },
        ),
        migrations.CreateModel(
            name='User_comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.comite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.user')),
            ],
            options={
                'verbose_name': 'Comite do Usuário',
                'verbose_name_plural': 'Comites do Usuário',
            },
        ),
        migrations.CreateModel(
            name='User_eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.eventos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.user')),
            ],
            options={
                'verbose_name': 'Evento do Usuário',
                'verbose_name_plural': 'Eventos dos Usúario',
            },
        ),
        migrations.CreateModel(
            name='User_grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_de_estudos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.grupo_de_estudos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.user')),
            ],
            options={
                'verbose_name': 'Grupo de EStudo do Usuário',
                'verbose_name_plural': 'Grupos de Estudo do Usuário',
            },
        ),
        migrations.CreateModel(
            name='User_nucleos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nucleos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.nucleos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.user')),
            ],
            options={
                'verbose_name': 'Núcleo do Usuário',
                'verbose_name_plural': 'Núcleos do Usuário',
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('local', models.CharField(max_length=50)),
                ('preco', models.CharField(max_length=9)),
                ('nome_produto', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.user')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.CreateModel(
            name='Reservar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venda', models.CharField(max_length=45)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.atendimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.user')),
                ('vendas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteifc.vendas')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
