# Generated by Django 5.2.6 on 2025-09-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteifc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='data',
            field=models.DateField(default='2025-09-17'),  # Corrigido para uma string válida de data
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atendimento',
            name='hora',
            field=models.TimeField(default='10:00:00'),  # Corrigido para uma string válida de hora
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='data',
            field=models.DateField(default='2025-09-17'),  # Corrigido para uma string válida de data
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),  # Corrigido para um email válido
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='hora',
            field=models.TimeField(default='10:00:00'),  # Corrigido para uma string válida de hora
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo_estudo',
            name='dia',
            field=models.DateField(default='2025-09-17'),  # Corrigido para uma string válida de data
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo_estudo',
            name='horario',
            field=models.TimeField(default='10:00:00'),  # Corrigido para uma string válida de hora
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservar',
            name='data',
            field=models.DateField(default='2025-09-17'),  # Corrigido para uma string válida de data
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendas',
            name='data',
            field=models.DateField(default='2025-09-17'),  # Corrigido para uma string válida de data
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendas',
            name='hora',
            field=models.TimeField(default='10:00:00'),  # Corrigido para uma string válida de hora
            preserve_default=False,
        ),
    ]
