# Generated by Django 5.2.6 on 2025-09-18 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteifc', '0002_atendimento_data_atendimento_hora_eventos_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservar',
            name='atendimentos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='siteifc.atendimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservar',
            name='atendimento',
            field=models.CharField(max_length=45),
        ),
    ]
